### ISSUE TITLE
FAHclient did not start

### ISSUE THREAD

**Issue by StephenTurley** [jkataja/cfn-foldingathome#2]
The FAHClient did not start and I had to restart the service before I could connect to the web interface. It also seems like its not configured to use the GPU. I assume I need to set <gpu v='true'/>

**Comment by jkataja** [comment]
I have added a 10 minute initial timeout with a call to signal success at the end of the instance initialization script. This means the stack creation will now fail if installation was not successful. Also, I have implemented a custom health check in case the Folding@home client stops with an error. Client is now started as systemd service and not init script packaged with the client. I hope the changes also avoid the client overwriting configuration file.

Please try again!  I believe these changes should make the template more robust. Meanwhile, getting a work unit requires some luck.

**Comment by jkataja** [comment]
Auto scaling group now expects success signal that is sent only after the client has been successfully installed the request. Closing.
